---
- hosts: all
  become: yes
  become_user: root
  user: vagrant
  gather_facts: False
  roles:
    - common

  # environment:
  #   https_proxy: "{{ lookup('env', 'https_proxy') }}"

- hosts: loadbalancers
  become: yes
  become_user: root
  user: vagrant
  roles:
    - nginx

- hosts: webservers
  become: yes
  become_user: root
  user: vagrant
  roles:
    - apache2
    - python2
    - pip/app
    - mod_wsgi_py2
    - mysql/client

- hosts: dbs
  become: yes
  become_user: root
  user: vagrant
  roles:
    - mysql/client
    - mysql/server
