---

- include_vars: main.yml

- name: install nginx_packages
  apt: 
    name: "{{item}}"
    state: present 
  with_items: "{{nginx_packages}}"

- name: set nginx.conf
  template: 
    src: /vagrant/playbook/roles/nginx/templates/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0644

- name: Start the nginx service
  become: yes
  service: 
    name: nginx
    state: restarted
    enabled: true

